Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Cell 1
import os
# make sure we're in /Users/carmenvanderlans/Information-Vis
os.chdir(os.path.expanduser("~/Information-Vis"))
print("cwd =", os.getcwd())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m      3[0m [38;5;66;03m# make sure we're in /Users/carmenvanderlans/Information-Vis[39;00m
[0;32m----> 4[0m os[38;5;241m.[39mchdir(os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser([38;5;124m"[39m[38;5;124m~/Information-Vis[39m[38;5;124m"[39m))
[1;32m      5[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mcwd =[39m[38;5;124m"[39m, os[38;5;241m.[39mgetcwd())

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/jettejohannadw/Information-Vis'

